layouts/partials/comments.html
layouts/post/single.html
layouts/post/summary.html

1. fix term url continue.
2. gitment id (issue label) should not be page date, will change with` .File.LogicalName`.

fixed term url and gitment issue label

---

exampleSite/config.toml
exampleSite/layouts/index.jsonfeed.json
layouts/partials/head.html

Add `[outputFormats.jsonfeed]` section in config.toml to enable json feed.
fix https://github.com/xianmin/hugo-theme-jane/issues/23

Add json feed

---

layouts/_default/terms.html

The error occurred when I tried to use Jane theme on new blog. 
```
 → hugo server -D
Building sites … ERROR 2018/04/02 22:15:28 Error while rendering "taxonomyTerm" in "": template: /tmp/blog/themes/hugo-theme-jane/layouts/_default/terms.html:42:19: executing "content" at <len $.Site.Taxonomie...>: error calling len: len of untyped nil
...
```
There is no error if there are any posts with tags already.

Fix access to tags when there are no tags

---

i18n/en.yaml
i18n/fr.yaml
i18n/pt.yaml
i18n/ru.yaml
i18n/zh-cn.yaml

As promised in #49, I added the french translation files. 
Let me know if I missed anything

i18n: Add fr translation

---

layouts/partials/header.html

feat: show language name in language chooser

---

layouts/shortcodes/youku.html

只是改动了 youku.html，稍微整理、改动了下，使其更为易用。
目前来看，这个youku的通用播放地址，有些内容还是无法播放，会提示参数错误，但是感觉能用的还是大多数。
关于此PR的 issue 是 https://github.com/xianmin/hugo-theme-jane/issues/87

对于youku的shortcode文件的代码的小改动

---

README.md

add blog site

---

exampleSite/config.toml
layouts/_default/baseof.html
layouts/partials/photoswipe.html
layouts/partials/scripts.html

photoswipe CDN

---

exampleSite/config.toml
exampleSite/full-config.toml

The current configuration is too complicated, I divided it into two configurations, maybe more friendly to the common users.

a simple config for common user

---

exampleSite/full-config.toml
i18n/en.yaml
i18n/zh-cn.yaml
i18n/zh-tw.yaml
layouts/partials/scripts.html
layouts/post/summary.html

See: https://help.disqus.com/developer/adding-comment-count-links-to-your-home-page

support comment count links for Disqus

---

README.md

Add mine to the blog list: [Potioneer's Essays](https://william-yeh.net/)

Add mine to the blog list

---

dev-config.toml
layouts/partials/comments.html

In this PR I add support for commento.io commentary system. It seems to be a good one. See how it looks like here: https://commento.io/.

Add commento support

---

layouts/partials/slideout.html

add safeHTML to logoTitle in slideout.html for mobile header

---

dev-config.toml
exampleSite/full-config.toml
layouts/partials/scripts.html
layouts/partials/search_google.html
layouts/partials/slideout.html

1. Fix the bug that the search button has not effect.
2. Allow custom title.

Fix search issues mentioned in #203.

---

SITES.md

Add http://duydo.me to sites using Hugo-theme-Jane

Add duydo.me as site using Hugo-theme-Jane

---

stackbit.yaml

Add some parameters for a new post.
- katex
- markup

fix stackbit.yaml for a new post

---

layouts/partials/footer.html

备案要求备案号为指向工信部网站的链接，修改以便可以使用以下的形式可以添加链接
```
customFooter = '<a href="http://beian.miit.gov.cn/" target="_blank">京 ICP 备XXXXXX 号 - 1</a>'
```

add safeHTML to customFooter

---

exampleSite/config.toml

I found mini typo at config.toml.

Fix typo 'Othewise' -> 'Otherwise'

---

layouts/partials/head.html

SEO check tool "Lighthouse" alert
-> viewport setting
https://github.com/GoogleChrome/lighthouse

fix: improve Lighthouse's score, accessibility

---

i18n/ja.yaml

feat: add Japanese translation

---

dev-config.toml
exampleSite/full-config.toml

cc @Zebradil for review, as he originally added it in dc96e1df4d8faadfe440a19b14385e0ea07d79c9.

Move Commento example from dev to full config

---

assets/sass/_partial/_pagination.scss

style: center pagination

---

.all-contributorsrc
SITES.md
dev-config.toml
exampleSite/content/post/other/creating-a-new-theme.md
exampleSite/content/post/other/english-preview.md
exampleSite/full-config.toml
i18n/es.yaml
i18n/fr.yaml
i18n/ja.yaml
i18n/pt.yaml
i18n/ru.yaml
i18n/zh-cn.yaml
i18n/zh-tw.yaml
layouts/shortcodes/series.html
stackbit.yaml

Also, update information related to my blog and contributions.

Add missing translation strings, update Russian, fix typos

---

.github/dependabot.yml

That will ensure that actions stay up-to-date automatically.
PR which would be created automatically after you'll merge it: https://github.com/paskal/hugo-theme-jane/pull/2

Add monthly dependabot updates to GitHub Actions
