config.toml, layouts/post/summary.html
Adds new Site Parameter "homeFullContent" which, when true, uses .Content
rather than .Summary while rending posts on the home page.
It's a little odd to render .Content from a template named summary.html but this was the most concise way I could think of.
=> Add option to show full .Content on home page

layouts/_default/section.html, layouts/_default/taxonomy.html
In line with [hugo pagination default](https://gohugo.io/templates/pagination/#configure-pagination), it allows not to set this configuration parameter and have correctly rendered tags and archives page.
Fixes #12.
=> Set archive-paginate default to 10

i18n/ru.yaml
Hi, $subj.
By the way, `linkToMarkDown` is not documented but present in code and translations.
=> Russian translation added

README-zh.md, exampleSite/config.toml, layouts/_default/terms.html, layouts/partials/head.html, layouts/post/single.html
在启用 uglyURLs  后，实际上tag和category的地址由：http://localhsot/tag/ 变成了 http://localhsot/tag.html
可主题中尚未处理，而同时Hugo本身无法将uglyURLs配置作为Site变量公开，所以只能折中使用添加自定义配置形式：
```toml
uglyURLs = true
[params]
uglyURLs = true
```
=> 修复启用uglyURLs时terms url 问题

i18n/en.yaml, i18n/es.yaml, i18n/ru.yaml, layouts/partials/post/i18nlist.html, layouts/post/single.html, layouts/post/summary.html
Hi!
I have an idea to show list of available translations somewhere. Currently I placed the list right under post title. It displays if there is at least one translation for the post. In example below I created post in three languages: English, Spanish and Russian.
For English version:
For Russian version:
What do you think?
=> [Proposal] Show list of available translations

README.md, exampleSite/config.toml, exampleSite/content/post/english-preview.md, exampleSite/content/post/jane-theme-preview.md, exampleSite/content/post/shortcodes-preview.md, exampleSite/content/post/syntax-highlighting.md, layouts/_default/single.html, layouts/_default/terms.html, layouts/partials/comments.html, layouts/partials/footer.html, layouts/partials/head.html, layouts/partials/pagination.html, layouts/shortcodes/music.html, layouts/shortcodes/youku.html, webpack.config.js
Hello!
This path removes trailing spaces (my editor removed them from files I've edited and I've applied the change to everything to prevent this from happening to someone else) and fixes render errors in case of undefined `.Site.Author.name` for `head` and `footer` partials - without this path they won't render at all, after it just problem lines won't be added.
=> Undefined .Site.Author.name fix and trailing spaces removal

exampleSite/config.toml
If you uncomment the json output lines, the rss output does not work (see https://github.com/xianmin/hugo-theme-jane/issues/69)
=> To not break the RSS output

exampleSite/config.toml
I think it's better to inform hugo newbies that it's necessary also to create a template file and not only to uncomment the lines in the config file
=> Add a note to JSON output

layouts/404.html, layouts/_default/terms.html, layouts/partials/header.html, layouts/partials/slideout.html, layouts/post/single.html, layouts/post/summary.html
Many links are broken in subsites of different languages. This fix that.
I also change `{{ "/" | relURL }}` to `{{ "/" | relLangURL }}` because it seems strange to redirect to default language when you click those links in a subsite of different language.
=> use relLangURL for multilingual support

layouts/partials/footer.html
As talked about in #75, current RSS link in multilingual environment is incorrect.
BTW, as I am new to Hugo development, I am not sure whether there is a better syntax than the two `with`s.
=> link to correct RSS URL, fix #75

dev-config.toml, exampleSite/config.toml, layouts/_default/terms.html, layouts/post/single.html, layouts/post/summary.html
See discussions here: https://discourse.gohugo.io/t/how-to-get-permalink-of-taxonomies-in-templates/12927
This PR allows users to modify the permalinks for tags and categories without breaking the links. E.g.,
```
[permalinks]
tags = "/tag/:slug/"
```
In addition, `params.uglyURLs` is no longer needed because now the URLs can be automatically inferred by the system even when `uglyURLs` = `true`.
=> remove hardcoded URLs for tags/categories

layouts/_default/terms.html, layouts/post/single.html, layouts/post/summary.html
Hugo v0.45 no longer supports three-argument form for `GetPage`.
(The two-argument form is supported in previous versions as well.)
=> fix API incompatibility for v0.45

layouts/partials/head.html
This disables google analytics when executing `hugo server`
=> disable google analytics on localhost

layouts/partials/head.html
See https://support.google.com/webmasters/answer/189077.
`<link hreflang="lang_code"... >` should point to translated pages.
=> fix `<link hreflang="lang_code"... >`

layouts/partials/comments.html
Prevent splitting Disqus threads for
`URL/?test=1`, `URL/?test=2`, `URL/?test=3`, etc...
=> don't split threads when query parameters exist

layouts/partials/scripts.html
不蒜子 JS 文件地址变了。
> 因七牛强制过期『dn-lbstatics.qbox.me』域名，与客服沟通无果，只能更换域名到『busuanzi.ibruce.info』！
=> fix busuanzi js url

layouts/partials/author_info.html
Previously, author description only supports raw texts. But maybe markdown support is useful.
=> allow using Markdown in author description

exampleSite/full-config.toml, layouts/partials/photoswipe.html, layouts/partials/scripts.html
If I enable publicCDN in `config.toml`, then click image in blog, the development tools  of web brower will prompt error info
>Uncaught ReferenceError: PhotoSwipeUI_Default is not defined' when use 'js/load-photoswipe.js
Upgrade photoswipe version to latest version (4.1.3) will solve this problem.
=> Upgrade photoswipe to latest version (4.1.3) to solve prompt 'PhotoSwipeUI_Default is not defined' 

layouts/partials/head.html, layouts/rss.xml
The new Hugo release brings some breaking changes:
> WARN 2019/04/18 00:34:11 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
> WARN 2019/04/18 00:34:11 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like:
{{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
And `rssLimit` requires update RSS template. Update to satisfy the compiler.
=> Fix compatibility issues with Hugo 0.55

exampleSite/content/post/jane-theme-preview.md
One might use double backticks plus one backtick here. So the page will be rendered `` `code` ``
=> Double backticks between backtick

layouts/partials/pagination.html
This probably fixes #222.
The current master version does not build when `paginateOriginalStyle = true`.
=> fix #222: pagination links

assets/sass/_partial/_post/_content.scss, layouts/shortcodes/figure.html
First commit remove word-break from post `a` tag, fixing #225. However, I didn't regenerated scss resources as I don't know how to do that properly: Readme have no instructions on that, we should fix it.
Second commit add `target` and `rel` params to figure shortcode, helping (or fixing) #223.
=> Remove word-break from post "a" tag, add "target" and "rel" params to figure shortcode

dev-config.toml, exampleSite/full-config.toml, layouts/index.html
Hugo v.0.57.0 存在打破性更改，修复首页文章列表相关内容
关于此PR的官方警告：[Demos with empty homepage and/or wrong posts list](https://github.com/gohugoio/hugoThemes/issues/682)
=> Fix: empty homepage or wrong posts list

README-zh.md, README.md, netlify.toml, stackbit.yaml
This pull request add's Stackbit to this Hugo theme. It add's the stackbit.yaml file which makes this theme work with several headless CMS automatically (including Forestry, NetlifyCMS, DatoCMS & Contentful) and it deploys the site to Netlify in 1 click.
You can try it out: https://app.stackbit.com/create?theme=https://github.com/stackbithq/hugo-theme-jane (note the "create with stackbit" button in the readme will import the theme from your repo so until the PR is merged it wont work)
I think this is really valuable and is a very low impact addition on your existing theme structure. Pretty much just the stackbit.yaml file. If you have questions or feedback I'm happy to discuss.
Risto
=> Add Stackbit Integration

layouts/partials/head.html
The RSS link is rendered incorrectly by default into an escaped version. This change corrects that.
=> Fix RSS link

i18n/es.yaml
Hello!
I'm native spanish speaker and I noticed some minor typos in the spanish translation.
I've fixed them and I also replaced some words like _tags_ to _etiquetas_ and _posts_ to _entradas_ as those are the ones we use in spanish speaking countries.
[Here's a reference.](https://es.wikipedia.org/wiki/Wikipedia:Etiquetas)
=> Fixed typos in the spanish translation

layouts/_default/terms.html
This PR adds a default layout for taxonomies.
Before this PR, when we add a new taxonomy(like "collection"), we will get an empty page at `domain/collections` which is really confusing and awkward.
With this PR, we will get a default layout just like `Category` and the leading title will be taxonomy itself.
This PR also sets the default i18n content of the taxonomy to the content itself. So that we don't need to update all the i18n files every time we add a new taxonomy.
I'm new to hugo and wonder if there's a better way to do this.
=> set default layout for taxonomies

layouts/partials/head.html
Deprecated here: https://github.com/gohugoio/hugo/issues/9172
Causes the following warning:
```
[opc@terrty ~/blog]$ docker-compose run build
Start building sites …
hugo v0.95.0-9F2E76AF linux/arm64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio
WARN 2022/03/28 22:11:03 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
```
=> Remove google_news usage

exampleSite/full-config.toml, layouts/partials/comments.html, layouts/partials/footer.html, layouts/partials/scripts.html, layouts/post/summary.html, stackbit.yaml
These changes are live on https://terrty.net, here is how comments and counter looks like:
Configuration options are taken from how Disqus comments work now in that theme.
=> Add Remark42 comments support

layouts/partials/scripts.html
I've made misconfiguration while embedding remark42, this PR fixes it. Now remark42 configuration won't be loaded on pages where neither comment form nor comments counter are present.
=> Don't embed remark42 on pages without comments form

README.md, go.mod
Technically go.mod is not necessary but it's nice to have. The instruction as a module works right now without go.mod added.
=> Add instructions about installing theme as a hugo module

layouts/partials/head.html, layouts/partials/scripts.html, layouts/shortcodes/figure.html
Check https://gohugo.io/functions/relurl/#input-begins-with-a-slash for details.
> If the input begins with a slash, the resulting URL will be incorrect when the baseURL includes a subdirectory. With a leading slash, the function returns a URL relative to the protocol+host section of the baseURL.
As a result, the customJS and customCSS feature was broken when baseURL includes a subdirectory like `https://example.com/blog`.
=> rm leading slash for relURL

layouts/partials/post/meta.html, layouts/partials/scripts.html
Previously, the comment counter was supposed to be displayed but did not. Now, it would work the same with the list of posts
and on the single post page.
Before and after, the main page:
Before, the post page:
After, the post page:
I presume when I added it initially, I thought the counter shouldn't be displayed on the post page. However, in reality, it is displayed, but JS code loading digits were not enabled.
=> Fix Remark42 comments count on the post page

layouts/_default/section.html, layouts/_default/taxonomy.html, layouts/partials/post/copyright.html, layouts/partials/post/meta.html
Previously, time representation in English was always used. Examples with Spanish below.
Post title. Before:
After:
---
Copyright. Before:
After:
---
Posts archive. Before:
After:
Tag page. Before:
After:
=> respect local format in the render

layouts/partials/mathjax.html, layouts/partials/scripts.html
Fixes #377 while also making it possible to stick to MathJax 2 if desired.
=> Update MathJax and put it in a separate partial layout that can be overridden

layouts/partials/comments.html, layouts/partials/comments/disqus.html, layouts/partials/head.html, layouts/partials/scripts.html
ERROR deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.133.0. Use hugo.IsServer instead.
ERROR deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.133.0. Use .Site.Config.Services.GoogleAnalytics.ID instead.
ERROR deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.133.0. Use .Site.Config.Services.Disqus.Shortname instead.
=> Fix use of deprecated symbols

assets/sass/_partial/_post/_header.scss
=> style: only add delimiters between categories

layouts/_default/single.html, layouts/partials/head.html, layouts/partials/post/copyright.html, layouts/partials/post/meta.html, layouts/post/summary.html
Fixes PR #372 which removed individual post author settings. This change maintains multi-author support by allowing author to be specified at the post level rather than only globally.
=> fix: restore per-post author override functionality

layouts/partials/post/meta.html
Currently Jane allows an author to disable the comments on individual articles.. However, the option does not remove the link to the comments. This PR removes the link if the author disables the comments on the specific article.
We use the same condition as:
https://github.com/xianmin/hugo-theme-jane/blob/1e476ccc61156dc87443f7011cd114a64491b4e1/layouts/partials/comments.html#L1
=> Remove comment link if there are no comments

assets/sass/jane.scss
Currently if you show the author info, the styling looks not great. Importing the partial style seems to fix the issue. It is not clear if there was a reason that author_info was not imported though.
=> Re-enable author-info styling

assets/sass/_partial/_post.scss, layouts/partials/comments/disqus.html
Closes #412.
This PR fixes the background of the Disqus comments in dark mode.
The issue is that the background of `iframe`s would become opaque if the inherited `color-scheme` is different from the embedded web page.
=> Fix Disqus in dark mode

layouts/partials/comments/disqus.html
In #413, a bug was introduced that incorrectly referenced the same thread id for all posts when reload is used. This PR fixes the issue.
=> Fix Disqus Thread Id
